version: "3.7"
services:
# IHM
  ihm-budgets:
    image: vzwingmann/gestion_budget_ihm:${BUDGET_VERSION}
    env_file:
      - ihm.env
    ports:
      - "4010:8080"
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "IHM"
    depends_on:
      - service-budgets
      - service-comptes
      - service-params
      - service-utilisateurs
    links: 
      - service-budgets
      - service-comptes
      - service-params
      - service-utilisateurs
    networks:
      - bdgt-net
      - log-bdgt-net
    
# Services
  service-budgets:
    image: vzwingmann/gestion_budget_services:budgets-${BUDGET_VERSION}
    ports:
      - "4020:8080"
    env_file:
      - services.env
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "SVC BUDGETS"
    depends_on:
      - service-comptes
      - service-params
    links: 
      - service-comptes
      - service-params
    networks:
      - bdgt-net
      - log-bdgt-net


  service-comptes:
    image: vzwingmann/gestion_budget_services:comptes-${BUDGET_VERSION}
    ports:
      - "4021:8080"
    env_file:
      - services.env
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "SVC COMPTES"
    networks:
      - bdgt-net
      - log-bdgt-net

  service-params:
    image: vzwingmann/gestion_budget_services:parametrages-${BUDGET_VERSION}
    ports:
      - "4022:8080"
    env_file:
      - services.env
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "SVC PARAMS"
    networks:
      - bdgt-net
      - log-bdgt-net
    restart: always


  service-utilisateurs:
    image: vzwingmann/gestion_budget_services:utilisateurs-${BUDGET_VERSION}
    ports:
      - "4023:8080"
    env_file:
      - services.env
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "SVC USERS"
    networks:
      - bdgt-net
      - log-bdgt-net
    restart: always
    
      
# Networks
networks:
    bdgt-net:
      driver: bridge
    log-bdgt-net:
      driver: bridge