version: "3.9"
services:
# IHM
  ihm:
    image: vzwingmabudget/gestion_budget_ihm_legacy:latest
    env_file:
      - ihm.env
    ports:
      - "5010:8080"
    restart: always
#    logging:
#      driver: gelf
#      options:
#        gelf-address: "udp://localhost:12201"
#        tag: "IHM"     
    depends_on:
      - service-operations
      - service-comptes
      - service-params
      - service-utilisateurs
    links: 
      - service-operations
      - service-comptes
      - service-params
      - service-utilisateurs

# Services
  service-operations:
    image: vzwingmabudget/gestion_budget_services:operations-${BUDGET_VERSION}
    ports:
      - "5020:8080"
    env_file:
      - services.env
    restart: always
#    logging:
#      driver: gelf
#      options:
#        gelf-address: "udp://localhost:12201"
#        tag: "SVC BUDGETS"             
    depends_on:
      - service-comptes
      - service-params
    links: 
      - service-comptes
      - service-params

  service-comptes:
    image: vzwingmabudget/gestion_budget_services:comptes-${BUDGET_VERSION}
    ports:
      - "5021:8080"
    env_file:
      - services.env
    restart: always
#    logging:
#      driver: gelf
#      options:
#        gelf-address: "udp://localhost:12201"
#        tag: "SVC COMPTES"     

  service-params:
    image: vzwingmabudget/gestion_budget_services:parametrages-${BUDGET_VERSION}
    ports:
      - "5022:8080"
    env_file:
      - services.env
#    logging:
#      driver: gelf
#      options:
#        gelf-address: "udp://localhost:12201"
#        tag: "SVC PARAMS"        
    restart: always

  service-utilisateurs:
    image: vzwingmabudget/gestion_budget_services:utilisateurs-${BUDGET_VERSION}
    ports:
      - "5023:8080"
    env_file:
      - services.env
#    logging:
#      driver: gelf
#      options:
#        gelf-address: "udp://localhost:12201"
#        tag: "SVC USERS"        
    restart: always