version: "3.9"
services:
# IHM
  ihm-budgets:
    image: vzwingmabudget/gestion_budget_ihm:snapshot
    env_file:
      - ihm.env
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - service-operations
      - service-comptes
      - service-params
      - service-utilisateurs
    links: 
      - service-operations
      - service-comptes
      - service-params
      - service-utilisateurs

# Services
  service-operations:
    image: vzwingmabudget/gestion_budget_services:operations-${BUDGET_VERSION}
    ports:
      - "4020:8080"
    env_file:
      - services.env
    restart: always
    depends_on:
      - service-comptes
      - service-params
    links: 
      - service-comptes
      - service-params

  service-comptes:
    image: vzwingmabudget/gestion_budget_services:comptes-${BUDGET_VERSION}
    ports:
      - "4021:8080"
    env_file:
      - services.env
    restart: always

  service-params:
    image: vzwingmabudget/gestion_budget_services:parametrages-${BUDGET_VERSION}
    ports:
      - "4022:8080"
    env_file:
      - services.env
    restart: always

  service-utilisateurs:
    image: vzwingmabudget/gestion_budget_services:utilisateurs-${BUDGET_VERSION}
    ports:
      - "4023:8080"
    env_file:
      - services.env
    restart: always